# based on https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest
FROM ubuntu:16.04
RUN apt-get update -qq && \
    apt-get install -qqy --no-install-recommends\
      curl \
      apt-transport-https \
      lsb-release \
      gnupg \
      ca-certificates
RUN curl -sL https://packages.microsoft.com/keys/microsoft.asc | \
    gpg --dearmor | \
    tee /etc/apt/trusted.gpg.d/microsoft.asc.gpg > /dev/null
RUN echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" | \
    tee /etc/apt/sources.list.d/azure-cli.list
RUN apt-key adv --keyserver packages.microsoft.com --recv-keys EB3E94ADBE1229CF
RUN apt-get update -qq && \
    apt-get install -qqy --no-install-recommends\
      azure-cli